name: CPUs

on:
  workflow_dispatch:

jobs:
  test-386:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Test
      run: GOARCH=386 go test -v -short ./...

  test-arm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - name: Set up
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Install QEMU
      uses: docker/setup-qemu-action@v3

    - name: Test
      run: GOARCH=arm64 go test -v -short ./...

  test-m1:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test
        run: go test -v ./...
